version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run:
          command: python3 manage.py test
          name: Test
      - run: docker-compose up
workflows:
  main:
    jobs:
      - build-and-test